### PR TITLE
rm'ed source archive from overlay; clone from github

### PR DESCRIPTION
**Pull request by JedMeister**
@qrntz here's what I mentioned to you on slack.

It builds successfully to `root.patched` but I haven't tested beyond there... Not being so familiar with composer, I'm not sure if the composer overlay stuff is still required? Or also needs update? Beat to handball it to you for your expertise! :smile: 

FWIW I noticed that they have a repo named [composer](https://github.com/magento/composer) but it's just got a composer file and some tests...

### CODE REVIEW

**Comment by spyrule** [comment]
When is the expected release date of this patch?

**Comment by l-arnold** [comment]
Re Magento patches these can be run on the current version on the TkL appliance.   Suspect version 14.2 will have up to date Magento image so likely no patch required.  

Sorry I am not reading the full thread.

________________________________

**Comment by JedMeister** [comment]
Hi @spyrule 

ETA for the v14.2 release of Magento (which will include this) is probably ~3 weeks +/-?! Only guessing though.

It will be 2 weeks at the absolute soonest as my colleague Alon is away on vacation and he manages the final publishing step, so that's blocked until he's back on board.

If you are planning on doing some development locally on Magento 2.1, or you plan to run it locally anyway, then you could download TKLDev and build an ISO yourself?! We have a [doc page](https://www.turnkeylinux.org/docs/howto-build-isos-with-tkldev) that covers using TKLDev to build an ISO.

 If you need an AMI or similar though, then you'll need to wait.

**Comment by spyrule** [comment]
@JedMeister Thank you very much for the information, looking forward to the new version!

**Pull request merged**
